# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: no-commit-to-branch
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-toml
      - id: check-json
      - id: check-symlinks
      - id: check-docstring-first
      - id: check-added-large-files
      - id: detect-private-key
  # ruff
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: 'v0.9.6'
    hooks:
      - id: ruff
        args: ['--config', 'pyproject.toml', '--fix', '--show-fixes']
      - id: ruff-format
        args: ['--config', 'pyproject.toml', '--diff']
      - id: ruff-format
        args: ['--config', 'pyproject.toml']
  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.1
    hooks:
      - id: blacken-docs
        additional_dependencies: [black==22.12.0]
        exclude: notebooks/
