name: Build documentation

on:
    workflow_dispatch:
    push:
        branches: [ main, master ]
env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  docs:
    name: Linux
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: 'Set up Node'
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: 'Install uv'
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.10"
          enable-cache: true
          activate-environment: true
          cache-dependency-glob: |
            pyproject.toml
            uv.lock

      - name: 'Set up Git'
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com
          echo Current branch: $BRANCH_NAME

      - name: 'Install'
        run: |
          yarn install
          # install setuptools < 81 to fix issue with pkg_resources
          uv pip install -e . --group docs "setuptools<81"

      - name: 'Build docs'
        run: |
          git fetch origin gh-pages
          mike deploy --push --alias-type=copy --update-aliases $BRANCH_NAME latest
