name: Build documentation

# suppress warning raised by https://github.com/jupyter/jupyter_core/pull/292
env:
  JUPYTER_PLATFORM_DIRS: "1"

on:
    workflow_dispatch:
    push:
        branches: [ main, master ]


jobs:
  docs:
    name: Linux
    runs-on: ubuntu-latest

    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ github.workspace }}/pw-browsers

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Set up Git
        run: |
          git config user.name ${{ github.actor }}
          git config user.email ${{ github.actor }}@users.noreply.github.com

      - name: Base Setup
        uses: jupyterlab/maintainer-tools/.github/actions/base-setup@v1
        with:
          python_version: "3.10"
          node_version: "20.x"
          dependency_type: "standard"

      - name: Build docs
        run: |
          git fetch origin gh-pages
          hatch -e docs run mike deploy --push --no-redirect --update-aliases main latest
